#pragma once

enum GameMode
{
	MAIN_MODE = 1,
	MISSION_MODE = 2,
	STRUCT_MODE = 3,
	MEMBER_MODE = 4,
	DETAIL_MODE = 5
};
enum ButtonFunction
{
	NORMAL_FUNCTION = 21,
	MISSION_FUNCTION = 22,
	STRUCT_FUNCTION = 23,
	MEMBER_FUNCTION = 24,
	RETURN_FUNCTION = 25
};
enum VisibleList
{
	NORMAL_BUTTON = 11,
	MISSION_BUTTON = 12,
	STRUCT_BUTTON = 13,
	MEMBER_BUTTON = 14,
	STRUCT = 15
};
enum MoveList
{
	ACTION_NORMAL = 1,
	ACTION_RETURN = 2
};
enum TypeList
{
	TYPE_DEFAULT = 0,
	TYPE_NORMAL = 1,
	TYPE_FIGHTING = 2,
	TYPE_FLYING = 3,
	TYPE_POSION = 4,
	TYPE_GROUND = 5,
	TYPE_ROCK = 6,
	TYPE_BUG = 7,
	TYPE_GHOST = 8,
	TYPE_STEEL = 9,
	TYPE_FIRE = 10,
	TYPE_WATER = 11,
	TYPE_GRASS = 12,
	TYPE_ELECTRIC = 13,
	TYPE_PSYCHIC = 14,
	TYPE_ICE = 15,
	TYPE_DRAGON = 16,
	TYPE_DARK = 17,
	TYPE_FAIRY = 18
};
enum MissionCondition
{
	PROGRESS = 0,
	STAN_BY = 1,
	COMPLETION = 2
};